//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EspacioDelimitado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EspacioDelimitado()
        {
            this.Monitoreos = new HashSet<Monitoreo>();
        }
    
        public int IdEspacioDelimitado { get; set; }
        public string Coord1 { get; set; }
        public string Coord2 { get; set; }
        public string Coord3 { get; set; }
        public string Coord4 { get; set; }
        public Nullable<bool> Habilitado { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> Eliminado { get; set; }
        public Nullable<int> IdLote { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> Indice { get; set; }
    
        public virtual Lote Lote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Monitoreo> Monitoreos { get; set; }
    }
}
