//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitoreo
    {
        public int IdMonitoreo { get; set; }
        public int IdEspacioDelimitado { get; set; }
        public bool Estado { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual EspacioDelimitado EspacioDelimitado { get; set; }
    }
}
