//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifa
    {
        public int IdTarifa { get; set; }
        public int IdLote { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public decimal PrecioFraccion { get; set; }
        public decimal PrecioFijo { get; set; }
        public decimal FraccionMinimaPrecioFijo { get; set; }
    
        public virtual Lote Lote { get; set; }
    }
}
